# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aeb598aa4b667f7c5fb84e1f20c3cebef797b09964159a74e019d7dd40da98234fc6a3e6158fbfcf948c32cf92f0ae192337428be4c1881f2d791750e456b0a8

test:
  secret_key_base: 0fd181eff8ad4965456ab310ffabeb0b2449d78b4184b88d281aecff13fb7d41f50c2c18187dc82df42e9236b359327802097c7e2c349240fcca4a3f151abf4f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
